alert("Escribe tres numeros");
let uno=prompt("Num1: ");
uno= parseInt(uno);
let dos=prompt("Num2: ");
dos= parseInt(dos);
let tres=prompt("Num1: ");
tres= parseInt(tres);
let nombre=prompt();
let apellidos=prompt();
console.log(nombre,apellidos);